# Generated by Django 5.0.3 on 2024-03-24 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'News catalog'},
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_description', models.TextField()),
                ('news_image', models.FileField(upload_to='news_images')),
                ('news_created_at', models.DateTimeField(auto_now_add=True)),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uni.categorymodel')),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'News catalog',
            },
        ),
    ]
