# Generated by Django 5.0.3 on 2024-03-30 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uni', '0002_alter_categorymodel_options_newsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'BG University', 'verbose_name_plural': 'University catalog'},
        ),
        migrations.RenameField(
            model_name='categorymodel',
            old_name='category_title',
            new_name='University_title',
        ),
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University_title', models.CharField(help_text='Write', max_length=50)),
                ('University_description', models.TextField()),
                ('University_image', models.FileField(upload_to='University_images')),
                ('University_created_at', models.DateTimeField(auto_now_add=True)),
                ('University_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uni.categorymodel')),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Info for categories',
            },
        ),
        migrations.DeleteModel(
            name='NewsModel',
        ),
    ]
